# Generated by Django 5.2.8 on 2026-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mocktestresult_studylog_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernote',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
