# Generated by Django 5.2.8 on 2026-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(default='Pro', max_length=50),
        ),
    ]
