# Generated by Django 5.2.8 on 2026-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
