# Generated by Django 5.2.8 on 2026-02-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_preregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='token',
        ),
        migrations.AddField(
            model_name='preregistration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
