# Generated by Django 5.2.8 on 2026-02-11 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_preregistration_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
